// An offline, bilingual visual review of the public landing. Accounts remain server-backed.
import {chromium} from '@playwright/test';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
const root=process.cwd(),target=process.argv[2]||'screenshots/vera-preview.html';
const browser=await chromium.launch({headless:true});const pages={};
const mime={'.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.woff2':'font/woff2'};
async function dataURL(url){const clean=url.split('?')[0];if(!clean.startsWith('/')||clean.startsWith('//'))return url;const file=path.join(root,'dist',clean);try{return 'data:'+(mime[path.extname(file)]||'application/octet-stream')+';base64,'+(await readFile(file)).toString('base64');}catch{return url;}}
let css='';
for(const lang of ['ar','en']){const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.addInitScript(l=>localStorage.setItem('store-language',l),lang);await page.goto(process.env.PREVIEW_URL||'http://localhost:3000',{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);await page.locator('.v-hero').waitFor();
 const sources=await page.locator('link[rel=stylesheet]').evaluateAll(nodes=>nodes.map(n=>new URL(n.href).pathname));
 if(!css){for(const source of sources)css+=await readFile(path.join(root,'dist',source),'utf8');const matches=[...css.matchAll(/url\((?:"|')?(\/[^"')]+)(?:"|')?\)/g)];for(const match of matches)css=css.replaceAll(match[0],'url("'+await dataURL(match[1])+'")');}
 pages[lang]=await page.locator('.v-shell').evaluate(async el=>{const clone=el.cloneNode(true);clone.querySelectorAll('.v-reveal').forEach(n=>n.classList.add('v-revealed'));clone.querySelectorAll('img').forEach(n=>{n.loading='eager';});return clone.outerHTML;});
 for(const match of [...pages[lang].matchAll(/src="(\/[^\"]+)"/g)])pages[lang]=pages[lang].replaceAll(match[0],'src="'+await dataURL(match[1])+'"');await page.close();}
await browser.close();
const html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VÉRA — Offline design preview</title><style>${css}\n.review-note{position:fixed;bottom:12px;inset-inline-end:12px;z-index:80;max-width:250px;font:11px/1.5 Arial,sans-serif;background:white;border:1px solid #d6c7b9;padding:10px 13px;color:#743f37;box-shadow:0 3px 12px #0001}.review-note button{border:0;background:none;float:left;margin-inline-end:9px;cursor:pointer}</style></head><body><div id="review-root"></div><aside class="review-note"><button onclick="this.parentElement.remove()" aria-label="Close">×</button>معاينة تصميم محلية · الحسابات والدفع تعمل في نسخة الخادم.<br>Offline design preview · Accounts require the server.</aside><dialog id="review-dialog" style="border:1px solid #b49473;padding:30px;max-width:380px;font:16px/1.8 Arial;color:#743f37"><p>هذه معاينة للتصميم. افتح المشروع وشغّل الخادم لتجربة إنشاء المتجر ولوحات الإدارة.</p><p>This is a design preview. Run the supplied project to use accounts and dashboards.</p><form method="dialog"><button>إغلاق / Close</button></form></dialog><script>const screens=${JSON.stringify(pages).replaceAll('<','\\u003c')};let language='ar';function render(){document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';document.getElementById('review-root').innerHTML=screens[language];document.querySelector('.v-language').onclick=()=>{language=language==='ar'?'en':'ar';render()};document.querySelector('.v-menu').onclick=()=>{const nav=document.querySelector('.v-nav');nav.classList.toggle('open');document.querySelector('.v-menu').setAttribute('aria-expanded',nav.classList.contains('open'))};document.querySelectorAll('a').forEach(a=>{const h=a.getAttribute('href');if(h==='/'||h==='/templates')a.onclick=e=>{e.preventDefault();h==='/'?window.scrollTo({top:0,behavior:'smooth'}):document.getElementById('templates').scrollIntoView({behavior:'smooth'})};else if(h?.startsWith('/#'))a.setAttribute('href',h.slice(1));else if(h&&!h.startsWith('#')&&!h.startsWith('mailto:'))a.onclick=e=>{e.preventDefault();document.getElementById('review-dialog').showModal()};});}render();</script></body></html>`;
await mkdir(path.dirname(target),{recursive:true});await writeFile(target,html);console.log('Offline review created:',target);
